version: "2"

services:
  sonarqube:
    build: sonarqube
    image: brunoe/sonarqube:develop
    depends_on:
      - db
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube9_data:/opt/sonarqube/data
      - sonarqube9_extensions:/opt/sonarqube/extensions
      - sonarqube9_logs:/opt/sonarqube/logs
      - sonarqube9_temp:/opt/sonarqube/temp
  db:
    image: postgres:14
    networks:
      - sonarnet
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql14:/var/lib/postgresql
      - postgresql14_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube9_data:
  sonarqube9_extensions:
  sonarqube9_logs:
  sonarqube9_temp:
  postgresql14:
  postgresql14_data:
