apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker-compose.yml convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
      - env:
        - name: POSTGRES_PASSWORD
          value: sonar
        - name: POSTGRES_USER
          value: sonar
        image: postgres
        name: db
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: postgresql
        - mountPath: /var/lib/postgresql/data
          name: postgresql-data
      restartPolicy: Always
      volumes:
      - name: postgresql
        persistentVolumeClaim:
          claimName: postgresql
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: postgresql-data
status: {}
